### ISSUE TITLE
can't get ssl to work

### ISSUE THREAD

**Issue by affiliatepayday** [wavesplatform/WavesExplorerLite#100]
I am running a custom build via docker using -p 4000:8080 

The I set my nginx proxy_pass to port 4000. 

All works great. 

When I try to do this using ssl cert however it returns a 500 error: 
SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream

I tried adding the ssl cert to the etc/nginx/default.conf

This returns:
connect() failed (111: Connection refused) while connecting to upstream

Never had this problem with my node, it just worked when I set my proxy pass to 6869 port. 

How do I get ssl working with the explorer.

**Comment by msmolyakov** [comment]
Did you try to open explorer without SSL? Does this work?

And could you give your nginx config and your run command for explorer docker image?

**Comment by affiliatepayday** [comment]
Yes it works perfect on the http side of things (so explorer is working). 

To run by default:

`docker run -d -e API_NODE_URL=http://127.0.0.1:6768 -e NODE_LIST=http://127.0.0.1:6768 -p 4000:8080 waves/waves-explorer`
 
The path to my certs is: ` /home/user/conf/web/ssl.hostname.(key|pem)` and these paths work until I do the proxy_pass. So I know the certs are working on the public side of things. 

This is the not working ssl nginx conf that returns 500 error in first message:

```
server {
    listen      public.ip:443;
    server_name hostname;
    ssl         on;
    ssl_certificate      /home/user/conf/web/ssl.hostname.pem;
    ssl_certificate_key  /home/user/conf/web/ssl.hostname.key;
    error_log  /var/log/apache2/domains/hostname.error.log error;

    location / {
        proxy_pass      https://public.ip:4000;
        location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|tif|tiff|css|js|htm|html|ttf|otf|webp|woff|txt|csv|rtf|doc|docx|xls|xlsx|ppt|pptx|odf|odp|ods|odt|pdf|psd|ai|eot|eps|ps|zip|tar|tgz|gz|rar|bz2|7z|aac|m4a|mp3|mp4|ogg|wav|wma|3gp|avi|flv|m4v|mkv|mov|mpeg|mpg|wmv|exe|iso|dmg|swf)$ {
            root           /home/user/web/hostname/public_html;
            access_log     /var/log/apache2/domains/hostname.log combined;
            access_log     /var/log/apache2/domains/hostname.bytes bytes;
            expires        max;
            try_files      $uri @fallback;
        }
    }
    include /home/user/conf/web/snginx.hostname.conf*;
}
```

This is the working default nginx conf:

```
server {
    listen      public.ip:80;
    server_name hostname ;
    error_log  /var/log/apache2/domains/hostname.error.log error;

    location / {
        proxy_pass      http://public.ip:4000;
        location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|tif|tiff|css|js|htm|html|ttf|otf|webp|woff|txt|csv|rtf|doc|docx|xls|xlsx|ppt|pptx|odf|odp|ods|odt|pdf|psd|ai|eot|eps|ps|zip|tar|tgz|gz|rar|bz2|7z|aac|m4a|mp3|mp4|ogg|wav|wma|3gp|avi|flv|m4v|mkv|mov|mpeg|mpg|wmv|exe|iso|dmg|swf)$ {
            root           /home/user/web/hostname/public_html;
            access_log     /var/log/apache2/domains/hostname.log combined;
            access_log     /var/log/apache2/domains/hostname.bytes bytes;
            expires        max;
            try_files      $uri @fallback;
        }
    }
    include /home/user/conf/web/nginx.hostname.conf*;
}
```

I also tried to use the -v flag to list the path with no success (but admit I have no clue what I am doing). 

`docker run -d -e API_NODE_URL=http://127.0.0.1:6768 -e NODE_LIST=http://127.0.0.1:6768 -v /home/user/conf/web:/app/home/user/conf/web -p 4000:8080 waves/waves-explorer`

**Comment by affiliatepayday** [comment]
I got this sorted. 

So my solution was:

first I had to

 `mkdir ./etc/letsencrypt/live` (this is inside the main folder of the explorer)

 Then I modified the `./etc/nginx/default.conf`
 
 I added 
 
```
  ssl         on;
  ssl_certificate      /etc/letsencrypt/live/ssl.hostname.pem;
  ssl_certificate_key  /etc/letsencrypt/live/ssl.hostname.key;
```
Then rebuild the docker

Then

 `docker run -d -e API_NODE_URL=http://127.0.0.1:6768 -e NODE_LIST=http://127.0.0.1:6768 -v /home/user/conf/web:/etc/letsencrypt/live -p 4000:8080 waves/waves-explorer`


 
 ssl working now :)
