### ISSUE TITLE
Feature request: add buyer / seller

### ISSUE THREAD

**Issue by ilyacherevkov** [wavesplatform/WavesExplorerLite#11]
Please add Buyer / Seller addresses when viewing exchange transactions

**Comment by beregovoy68** [comment]
Hey Ilia,

What page you are talking about? If it's a block page (like here: http://wavesexplorer.com/blocks/805850), then buyer and seller were there for ages, but with different names (from & to).

I've changed exchange transactions table header, so now it should be more clear.

Cheers

**Comment by ilyacherevkov** [comment]
Hello @beregovoy68 

Take a look e.g. at this transaction: http://wavesexplorer.com/tx/7DcQD27SwW9LCcHgcifFSUE5W83NP1JJ7CTqBPUZgmHM

There is no buyer / seller address. Block page has it indeed

**Comment by beregovoy68** [comment]
Good catch, thanks! 

Fixed this in version 1.1.5. Ride on Waves!
