### ISSUE TITLE
Attachment of Transaction isn't decoded 

### ISSUE THREAD

**Issue by wavesexpuser** [wavesplatform/WavesExplorerLite#12]
Could you please decode the Attachment of Transaction http://wavesexplorer.com/tx/3N8FUsvdVphg7G27LfaU6T2kaLEBWpiGnCHZt5r3oJjM like https://wavesdesk.com/tx/3N8FUsvdVphg7G27LfaU6T2kaLEBWpiGnCHZt5r3oJjM or this can generate some issue?

Thanks

**Comment by beregovoy68** [comment]
It's already implemented. Check your link again.
