### ISSUE TITLE
Only display my portion of mass payments

### ISSUE THREAD

**Issue by blmatthews** [wavesplatform/WavesExplorerLite#14]
When I receive a mass payment, the transaction in the transaction list has an Amount In equal to the entire amount sent in the payment, while I (probably) only received a fraction of that. I can click on the transaction ID and find my address, but that seems like extra work the explorer should be doing, being I rarely if ever care about the total amount sent in the transaction, just my portion of it (and if, for some reason, I do care, I can look at the transaction itself for that).

See https://wavesexplorer.com/address/3P7EMPkwVv7rcBk8evCdaZxbeDit417PDtg for some examples.

**Comment by beregovoy68** [comment]
Hey,

This feature has already been implemented in current version of Waves Explorer.
