### ISSUE TITLE
Display wallets with coins

### ISSUE THREAD

**Issue by tkowalczyk** [wavesplatform/WavesExplorerLite#15]
It is possible to display all wallets holding specified coins (personal coins created on WAVES platform)?

**Comment by beregovoy68** [comment]
Hey,

Current Explorer implementation doesn't have it's own backend and uses only node public API. It means that it's impossible to show any cumulative statistics at the moment, unfortunately.

**Comment by tkowalczyk** [comment]
Ok thanks, so it is possible to do it with my own? is there some helpful api endpoint?

**Comment by beregovoy68** [comment]
There is no any API method for showing all wallets holding a specified coin (or coins). The only way of implementing this is scanning blockchain.

**Comment by tkowalczyk** [comment]
ok thank you
