### ISSUE TITLE
No transaction information is displayed in testnet

### ISSUE THREAD

**Issue by suhamera** [wavesplatform/WavesExplorerLite#17]
Failed to load transaction info in Google Chrome browser in Testnet, example: [https://wavesexplorer.com/tx/5tEWptnG27iiyXgGNqanzofJZcDv1QufS1Q78vnrK5mY](url)

**Comment by tsigel** [comment]
U need change network byte to testnet in the first line menu on the left side.

**Comment by beregovoy68** [comment]
Please use this link to view this transaction:
https://wavesexplorer.com/testnet/tx/5tEWptnG27iiyXgGNqanzofJZcDv1QufS1Q78vnrK5mY
