### ISSUE TITLE
Testnet Faucet is not working

### ISSUE THREAD

**Issue by khaker666** [wavesplatform/WavesExplorerLite#19]
Testnet Faucet is not working

> State check failed. Reason: Attempt to transfer unavailable funds: Transaction application leads to negative waves balance to (at least) temporary negative state, current balance equals 10140210, spends equals -10000100000, result is -9989959790

**Comment by beregovoy68** [comment]
Faucet address is temporarily out of money. It will get back soon!

**Comment by beregovoy68** [comment]
Faucet is ready
