### ISSUE TITLE
Unconfirmed transactions out of control

### ISSUE THREAD

**Issue by deemru** [wavesplatform/WavesExplorerLite#20]
As the main page become auto updated, you should provide less information about unconfirmed transactions, especially when there is more than 100 unconfirmed transactions.

If there is a lot of unconfirmed transactions, you can display just the number.

Otherwise the main page is unusable if there is a lot of unconfirmed transactions.

**Comment by beregovoy68** [comment]
Thanks for reporting that! 

We're currently working on the implementation. The idea is to display 25 transactions maximum as a short term solution. Long term we probably won't show transactions from utx as it doesn't have too much sense. Utx pool size should be enough to understand network load level.

Stay tuned.

**Comment by beregovoy68** [comment]
Implemented unconfirmed transaction limit of 25 items. This feature was released back in April 2019.

Enjoy!
