### ISSUE TITLE
transactions api pagination

### ISSUE THREAD

**Issue by roccomuso** [wavesplatform/WavesExplorerLite#27]
Don't know if is the right place to open this issue.
I'd like to know if there's a way to paginate returned txs by waves explorer api.

I'm referring to this endpoint specifically `https://nodes.wavesplatform.com/transactions/address/${address}/limit/${limit}`

**Comment by jahsus-waves** [comment]
Hello, roccomuso! we've already implemented transactions pagination in explorer

**Comment by roccomuso** [comment]
Are you talking about API?
can you link doc or give some hints?

**Comment by beregovoy68** [comment]
Hi Rocco,

If you asked about API here is the answer: pagination exists, but not documented clear enough.

You can find it here: https://testnode2.wavesnodes.com/api-docs/index.html#!/transactions/addressLimit 
Query parameter `after` says 'give me ${limit} transactions starting from transaction with id=${after}'

Does it make sense for you?

**Comment by roccomuso** [comment]
Yes that's it.
The issue is I'd like to use the `after` param as a cursor to get recent txs. But in order to do that I should have txs returned ASC by timestamp and not DESC by timestamp.

**Comment by beregovoy68** [comment]
Currently you can't change transaction ordering.

If you still need that functionality please create an issue in [Waves node](https://github.com/wavesplatform/Waves) project describing your use case.

Cheers

**Comment by roccomuso** [comment]
Ok, thanks, opened: https://github.com/wavesplatform/Waves/issues/2622
