### ISSUE TITLE
Sender/Recipient address

### ISSUE THREAD

**Issue by trim777** [wavesplatform/WavesExplorerLite#5]
In my Waves Wallet (downloaded as extension in google chrome) I see all addresses in this format:
3P6CNkW.........
3PDCx...........
but when I trying to search this wallet in waves explorer here: http://wavesexplorer.com
I need to write address with 1W in front of address, for example:
1W3P6CN...........
1W3PDCx...........
Can you fix this?

**Comment by beregovoy68** [comment]
It was fixed around last summer.
