### ISSUE TITLE
MobileGo Tokens haven't been received

### ISSUE THREAD

**Issue by mjbayly** [wavesplatform/WavesExplorerLite#6]
Hi there

I transferred MobileGo tokens from my Waves wallet nearly a day ago and the token haven't shown in my wallet yet. Anybody able to help me understand why? Screenshot below

![image](https://user-images.githubusercontent.com/29106686/27101776-25a43f4a-50d7-11e7-883b-ed3abaec82e5.png)

**Comment by beregovoy68** [comment]
Hi,

If you are able to see the transaction in Waves Explorer, it means that transfer has succeeded and the wallet will show it sooner or later. If you still don't see your transaction, please ask Waves Support.
